### ISSUE TITLE
Access Denie

### ISSUE THREAD

**Issue by jayzhou3** [austincunningham/keycloak-express#5]
Listening at http://localhost:8000
Could not obtain grant code: Error: Grant validation failed. Reason: failed to load public key to verify token
Could not obtain grant code: Error: Grant validation failed. Reason: failed to load public key to verify token
Not enough time elapsed since the last request, blocking the request
Could not obtain grant code: Error: Grant validation failed. Reason: Cannot read property 'then' of undefined
Could not obtain grant code: Error: Grant validation failed. Reason: failed to load public key to verify token

Why your branch is not working at all

**Comment by austincunningham** [comment]
Thanks updated 
https://github.com/austincunningham/keycloak-express/blob/3fbca117795850505b4dbe0b56c506c162ad7182/package.json#L11
seems to fix this.
